### PR TITLE
 try fixing #480

### PR DESCRIPTION
**Pull request by rong4188**
Cell border is not printed when a cell has rowspan which breaks page

### CODE REVIEW

**Comment by simonbengtsson** [comment]
It seems this does not actually resolve #480. The issue that can currently be seen in the rowspan and colspan example is still there when running with this fix applied. Can you send me an example of an issue that gets resolved with this fix?

**Comment by rong4188** [comment]
Hi @simonbengtsson ,
I just made a fiddle https://jsfiddle.net/tjm1apc9/ which used the master branch of my fork.

Cheers,
Roni

**Comment by rong4188** [comment]
@simonbengtsson 
and this is the rowspan and colspan example with the fix applied.
https://jsfiddle.net/p7x2nf50/

**Comment by simonbengtsson** [comment]
Awesome! Seems like the issue you were experienced is fixed! Still looks like the issue in the colspan rowspan example is still there though?

Screen Shot 2019-07-11 at 09 33 02

**Comment by simonbengtsson** [comment]
I'll review the code a bit and then likely merge it. Can you resolve the conflicts? You can simply remove the package-lock.json and the dist files from the pull request.

**Comment by npgeomap** [comment]
Just saw that you are working on this "page break colspan issue", wondering if it's possible to **repeat the colspan content after a page break**. Like this:
repeatRowSpanContent

**Comment by simonbengtsson** [comment]
Certainly doable @npgeomap. We should probably add it as an option though and not as default?

**Comment by rong4188** [comment]
Well, I think it might cause trouble when it has multiple lines of text which also breaks through pages. I didn’t aware of any easy solution for that actually.

**Comment by simonbengtsson** [comment]
Very true actually. Didn't think of that.

**Comment by npgeomap** [comment]
Good point @rong4188 therefore absolutely optional as @simonbengtsson mentioned. 
Should I create a new feature request?

**Comment by simonbengtsson** [comment]
Sure! I have a feeling no one will look at it for the foreseeable future so if you want it I would take a shot at a PR as well 👍

**Comment by rong4188** [comment]
I just found I stupidly edited everything in my master branch, so that it is very hard for me to remove some changed files from the pr. the conflicts are resolved anyway, so if this pr is merge-able can you please merge them all in then rebuild it to overwrite my dist files and package-lock.json file?

Thanks,
Roni

**Comment by simonbengtsson** [comment]
Perfect 👍

**Pull request merged**
