### PR TITLE
Improve width distribution to prevent word breaking

### PR DESCRIPTION
**Pull request by simonbengtsson**

### CODE REVIEW

**Comment by mmghv** [comment]
First of all, after you removed `hasSentence`, it worked on the example that was given in the issue and gave the exact result as the hook solution .. so great start.

Now, I'm following the logic line by line and found some issues, some are potential bugs and some are not necessarily bugs so we need do discuss them before applying any changes.

Also lets agree that the changes will be made from my end (after discussing) by pushing to this branch to avoid conflicts and because I'm studying all scenarios and I need to keep focus on each scenario .. lets get this "width calculations" done once and for all :+1:

**Comment by mmghv** [comment]
First I want to do some refactoring and renaming of basic elements before moving forward :

`cell.longestWordWidth` name is misleading as it counts for `padding`, it's more like a "minimal allowed width", I believe it's better to utilize `cell.minWidth` for that and get rid of `cell.longestWordWidth` state, so `cell.minWidth` will actually mean the "minimal allowed width" which will be the lesser of `cell.styles.minCellWidth` or `longestWordWidth + padding`

What do you think? should I apply this change?

**Comment by simonbengtsson** [comment]
Sounds great! Regarding longestWordWIdth we might need minWidth as it is now as well if the columns still does not fit page after we have reduced all columns to the longestWordWidth? But agree it is a poor name that would be nice to improve!

**Comment by simonbengtsson** [comment]
I would prefer doing as many refactorings as possible on master. I think it would be optimal if we could somehow make this a feature flag that is in master, but not enabled. If it is something I've learnt to avoid more than anything it is long lived feature branches. I tried to simply comment out the resizeSentencesColumns there seem to be some issues with the new resizeSentences as well preventing it to be merged. Will need to sort that out first.

**Comment by mmghv** [comment]
Then we first need to agree on what should happen if the table doesn't fit the set "table width" (be it a defined width or the default width of the page - the margin) .. if the table doesn't fit this width after adhering to the "longestWord" rule, what should happen?

1- let it grow as needed (what HTML does)
2- shrink the table (causing a definite word-break) but adhering to `cell.styles.minCellWidt` even if it exceeds the allowed size
3- shrink the table to fit the allowed size even if it breaks  `cell.styles.minCellWidt`

**Comment by mmghv** [comment]
You mean this is a problem preventing the merge right now? github says that there's not conflicts.

I will test it locally to see if there's a problem and what can we do about it.
About the feature branch, I didn't get what do you mean by `feature flag` and what is your concern here? anyway this is not a long-lived branch .. it will be merged as soon as it's finished which is pretty soon .. I'm all ready to get it done with this feature.

**Comment by simonbengtsson** [comment]
I think 2 and 3 are both good options. Currently the plugin uses 2 and logs an error to console if even word-break does not help in making the table width less than page width.

If we would go for 1 (ie not do any word-break if needed) I think it would be backwards incompatible with many of the tables I've written and assume others have done as well.

**Comment by simonbengtsson** [comment]
Awesome! My concern was just about long lived feature branch so if you are almost ready to merge then it's all good and you can ignore what I said about feature flag 👌Not a conflict, a bug causing one of the tables in the "Long content" to have a too small width.

**Comment by mmghv** [comment]
Don't worry about this bug, we will refactor and test & fix the bugs.
About the table shrink, lets keep `2` then .. later we could add a table-level option to never break words if needed.

**Comment by mmghv** [comment]
One other thing, I want to add a folder named "local-example" which will contain a basic example and then added to `.gitignore` so one can easily scrap a test example for a specific scenario

Also this has a great benefit that allows you to easily compare the example with the previews version of `AutoTable` by launching the example using the `file` protocol vs the live server

**Comment by simonbengtsson** [comment]
Sounds great 👌Not sure I understood this however:

> Also this has a great benefit that allows you to easily compare the example with the previews version of AutoTable by launching the example using the file protocol vs the live server

What do you mean with preview version? The examples started with `npm start` should already be using the latest src files thanks to the webpack dev server?

**Comment by mmghv** [comment]
Yes, when you browse to `http://localhost:9000/` the examples will be live using the latest changes, but if you open "index.html" directly in the browser, you will be using the already built dist file from the previous version .. that's a great trick to see what effects your changes may have done compared to the previous build.

**Comment by mmghv** [comment]
For example it was easy to see what you mean by the "long content table" bug by comparing the example against the old version this way

**Comment by simonbengtsson** [comment]
Aha! Make sense!

**Comment by mmghv** [comment]
Sorry, I pushed "local-examples" to `master` and tried to rebase this branch on master, found that it rewrote history so I redone the rebase and did a normal "merge" from `master`.

please tell me if you faced a problem pulling the changing into your local repo

**Comment by simonbengtsson** [comment]
No worries! Rebase ie rewriting history instead of merge commits in PRs are best practice though right? 

Both master and word-overflow branches pulled without issues btw 👌

**Comment by mmghv** [comment]
Yeah merge is the best practice but it adds additional commit, rebase is cleaner but it rewrites history, so you should only do it locally on un-pushed commits.

I knew that rebase will re-write history, but because I'm the only one pushing to this branch now I though it's ok, but found that when pulling (on another repo clone, simulating your local repo) it counted the old commit as a local commit that needed to be pushed, so I rebased again on the old commit to prevent that, One have to make mistakes to learn :D

**Comment by simonbengtsson** [comment]
Yes agree that rewriting history is fine in this branch. We constantly rebase our pull requests at work so at the rare instances two people are working on one pull request we use `git reset --hard origin/branch-name` instead of pulling whenever necessary. I think I prefer that to unnecessary merge commits.

**Comment by mmghv** [comment]
What do you think about `minReadableWidth` as a rename of `longestWordWidth` ?

**Comment by simonbengtsson** [comment]
minReadableWidth is perfect! 🎉

**Comment by mmghv** [comment]
There's a bug in using `entries()` and splicing the columns array :

```js
  for (const [i, column] of entries(columns)) {
    const width = column.getMaxCustomCellWidth()
    if (width) {
      column.width = width
      columns.splice(i, 1)
    }
  }
```

When you splice, the columns indices gets missed up, 
if you splice column 3 then splicing the next column will actually splice column 5 and not 4.

I'm thinking about using the opposite approach, starting with an empty array and filling it up with columns that needs to get resized .. this way it will be :

1- more intuitive
2- will eliminate the need to use array.slice() to copy the initial array
3- will eliminate the need of `entries()` filler method

What do you think?

**Comment by simonbengtsson** [comment]
Sounds good!

**Comment by mmghv** [comment]
Now I'm only using one `resizeColumns()` function, should I move it to `widthCalculator.ts` and delete `columnResizer.ts.` module?

**Comment by simonbengtsson** [comment]
Nice! Maybe it's easier to test if we keep them separate?

**Comment by mmghv** [comment]
It's just that, it's only a 23 lines function, I don't think we should put it in a separate file.
I'll keep it not separated and after we're done with the rest of stuff if you see it should be separated then we separate it

**Comment by mmghv** [comment]
In my opinion, if any thing should be separated, it's the `applyRowSpans()` and `applyColSpans()` methods.

**Comment by simonbengtsson** [comment]
Sounds good 👌

**Comment by mmghv** [comment]
I'm done, just have one question :

```js
// Add 1 to minWidth as linebreaks calc otherwise sometimes made two rows
column.width = column.minWidth + 1 / state().scaleFactor()
```

Why are you adding 1 here? I don't want to use it because size will not be correct then
I still need to do some testing with cell borders and colspans, but I need to push this commit without the `+1` what do you think?

**Comment by simonbengtsson** [comment]
The reason it was added was that for example the minimal example otherwise made two rows of things that should be on one line. If that does not happen you can remove it.

**Comment by mmghv** [comment]
Yeah it doesn't.

Please review the new commit, I'll do more testing but the logic is robust now

**Comment by mmghv** [comment]
I exported the `resizeColumns()` method to include it in the testing, tell me what you think

**Comment by simonbengtsson** [comment]
Looks great to me! Pushed a minor fix to prettier formatting and removed the gitignored file which I assume you accidentally pushed?

**Comment by mmghv** [comment]
Why you removed the `basic` local example file? I added it to be used as a base file to build your test case on.

By the way, I found a bug in the new calculations .. working on it now.

**Comment by mmghv** [comment]
Something to think about while I fix the bug, why are you calling the `didParseCell` hook twice for each cell in `inputParser.ts` ? once before parsing cell width and once after finishing the parsing.

I think it's wrong for a hook to be called twice for a cell, the first time (before the parse) is when you would be able to edit cell content and the with and resizing will get calculated currently, but the second time if you edit the content the size will not get calculated currently.

**Comment by simonbengtsson** [comment]
Oops! Removed the extra call to didParseCell now. Nice catch.

Oh, local-example is supposed to be in git? Should remove it from gitignore then?

**Comment by mmghv** [comment]
> Removed the extra call to didParseCell
Actually you removed the one that would allow the user to edit cell content, other one could be the correct one because it's called last after cell is parsed, but won't allow the user to edit cell content and still get width calculation for the edited content

> local-example is supposed to be in git? Should remove it from gitignore then?
I tracked `basic.html` so you would have a base example to copy & build on, but added `local-example` to gitignore so you still get other files you add ignored.

**Comment by mmghv** [comment]
Also note that this duplicate hook call was there for a long time ..

**Comment by simonbengtsson** [comment]
Damn it. How did I even manage to maintain this plugin without your code reviews. 🙈

Removed the other didParseCell now. It should be fine since willDrawCell should be used for other purposes then changing cell styles or cell content.

Also added back the local example, but in examples/local this time (if you don't mind).

**Comment by mmghv** [comment]
Haha don't say that, you did pretty good job in this plugin
Also now both called are removed, you need to revert first one, but about using the hook for other purposes then we should think about it, because the first location is good for editing content but the second one might be better for other stuff .. maybe we need another hook name? this need a study for the life-cycle.

> Also added back the local example, but in examples/local this time

That makes more sense actually

**Comment by simonbengtsson** [comment]
Hahaha 🙈Fixed. 

Sounds good to think an extra time about the lifecycle. I reworked the hooks for v3 of the plugin and with the three cell hooks that exists now (didParseCell, willDrawCell and didDrawCell) I've yet to see or come up with a use case that is not supported.

**Comment by mmghv** [comment]
Ok lets rethink it after we finish this one.

By the way don't  merge this pull request until I'm done with all tests an refactoring .. I'll tell you when it's ready for merge.

Also after merging don't release a new version .. we might want to do other stuff .. so lets discuss it first .. I have at least couple of small improvements that needs to be done but in another pull request.

**Comment by mmghv** [comment]
Reverted removal of extra call to `didParseCell`, will remove it in its own PR to add more info for future reference.

**Comment by mmghv** [comment]
Fixed consistent distributions, now the algorithm is pretty stable :ok_hand: .. will move forward for testing with margin, borders and colspans.

**Comment by simonbengtsson** [comment]
🎉

**Comment by mmghv** [comment]
Ok all done + testing, works very well and mimics html for the most part, except for borders and colspans which don't contribute to width calculations .. they need their own round of improvement.

PR is ready for merge now, review it for the last time then merge it.

By the way, here's the original example file you can test it .. run it in localhost vs in file system to check the differences :

[work-break example.zip](https://github.com/simonbengtsson/jsPDF-AutoTable/files/4418173/work-break.example.zip)

*(extract it in `examples/local`)*

**Comment by mmghv** [comment]
If you could, try squash couple of the commits that where done and reverted, otherwise don't bother.

Also don't release a new version after merging .. we still need to remove duplicate hook call or see what are we going to do about it.

**Comment by simonbengtsson** [comment]
Will review and merge during the day. Sorry for the delay. About the scenario mentioned it be nice to support better! At the same time we currently shrink the columns by the ratio of how wide they are so should at least work partially.

**Comment by simonbengtsson** [comment]
Really awesome stuff! Reviewed, did some additional testing and merged now 🎉 Also pushed the removal of the duplicate didParseCell call which I think should not affect anyone. Time for release with those two things as changelog?

**Comment by mmghv** [comment]
Great!
Yeah lets tag a release, I've got an idea to solve the scenario mentioned earlier, I might send a PR later.

**Comment by simonbengtsson** [comment]
Awesome!

**Comment by mmghv** [comment]
There seems to be a new problem with TS example in `examples\typescript\index.ts` that gets triggered when running dev server :

```
ERROR in jsPDF-AutoTable\examples\typescript\index.ts(9,40)
TS2307: Cannot find module 'jspdf-autotable'.
```

Please check it

**Comment by simonbengtsson** [comment]
How do you run the dev server? It doesn't seem to be any errors for me when using `npm start`? 🧐It's most likely related to me removing the include option in tsconfig so can add it back. Still interesting though.

**Comment by mmghv** [comment]
I do `npm start` then the examples open in `http://0.0.0.0:9000/`, I change it to `http://localhost:9000/` then I find the error both in the terminal and the devtools console.

By the way, why does the server opens in `http://0.0.0.0:9000/` and not localhost? did you configure it this way for a certain reason or am I missing something?

**Comment by simonbengtsson** [comment]
I configured it to 0.0.0.0 to support virtual machines for testing with internet explorer. Does that not work for you?

**Comment by mmghv** [comment]
No it doesn't, I'm working on win 7, it's not a big deal tho.
By the way, not the error is gone after your commit :+1:

**Comment by simonbengtsson** [comment]
Weird. Both localhost and 0.0.0.0 seems to work for me without the include option. 

Changed the "start" command to use localhost now and added a new "start-external" for testing with virtual machines etc. The 0.0.0.0 solution is documented [here](https://webpack.js.org/configuration/dev-server/#devserverhost) so it's a little weird it doesn't work for you. Do you think it's a windows issue? I'm running mac.

**Comment by mmghv** [comment]
Yes it's most certainly that windows doesn't support `0.0.0.0` as a localhost address

**Pull request merged**
