### PR TITLE
Export hook data types;

### PR DESCRIPTION
**Pull request by Never7Dice**
https://github.com/simonbengtsson/jsPDF-AutoTable/issues/720

### CODE REVIEW

**Comment by simonbengtsson** [comment]
Nice! Although the dist files are automatically generated when building a release. Can you submit one that doesn't change the didt files?

**Comment by Never7Dice** [comment]
Sorry for modifying dist, I didn't notice.
Can you please do it, please? I cannot find a file where you define which stuff is getting to the build. Classes at HookData.ts are already marked as exported, but they don't get exported in the build, unlike the config.ts and common.ts ones. I don't understand why it is so...

**Comment by simonbengtsson** [comment]
I think you need to reexport them from the main.ts file if I remember correctly. But you can check the lib used to generate the types if that doesn't work.

**Comment by Never7Dice** [comment]
So it should be manually re-exported in main.ts like this? (it works, I tested just now)

image

**Comment by simonbengtsson** [comment]
Looks about right to me!

**Comment by Never7Dice** [comment]
Ok, done, review and merge. Rebuild lib yourself, because my packager version is different from yours and produces 10000 changes to js.

**Comment by Never7Dice** [comment]
@simonbengtsson

**Comment by Never7Dice** [comment]
@simonbengtsson hello, review and merge, please :D

**Comment by alecarn** [comment]
We also need to access HookData. @simonbengtsson What the status of this PR, this look fine to me?

**Pull request closed without merging**
