### PR TITLE
adding dashed cell border styles

### PR DESCRIPTION
**Pull request by prpateldev**
adding support for dashed style border in cell
please check column style example
suggestions are welcome

### CODE REVIEW

**Comment by prpateldev** [comment]
it showing me in hacktoberfest for this pull request

Ineligible Repository
Your PR was submitted to a repository that is not participating in Hacktoberfest. Maintainers of the repository can add the "hacktoberfest" topic to their repository if they wish to participate.

I think some actions required from your side pleas help
Thanks :)

**Comment by simonbengtsson** [comment]
Done 👌

**Comment by prpateldev** [comment]
Thanks,
But it still show me this for my both open pull request

Pending
Your PR has not yet been accepted by a maintainer. A maintainer can accept your PR by merging it, adding the "hacktoberfest-accepted" label to it, or approving it.

no worries take your time to check and merge :)

**Comment by prpateldev** [comment]
@simonbengtsson please review this pr and merge or suggest changes :)

**Comment by prpateldev** [comment]
@simonbengtsson I have done with this pr, you can check and merge it

**Comment by simonbengtsson** [comment]
Sorry for the extreme late review. Looks great! If you still want to work on getting this merged feel free to reformat code with prettier and fix the merge conflict (probably adding back a working column styles example or adding usage somewhere).

**Comment by prpateldev** [comment]
> Sorry for the extreme late review. Looks great! If you still want to work on getting this merged feel free to reformat code with prettier and fix the merge conflict (probably adding back a working column styles example or adding usage somewhere).

Thanks for merging my other pr's and give me some time Ill fix it.

**Comment by simonbengtsson** [comment]
Closing for now, but if conflicts are fixed lets reopen 👌

**Pull request closed without merging**
