### PR TITLE
eliminate scenarios where less than zero remaining lines are printable

### PR DESCRIPTION
**Pull request by tarekis**
It can happen that the result of `remainingLineCount` is below zero; since [`Array.splice`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/splice) with negative starting values starts splicing at the arrays' **end** and is used with `remainingLineCount` [here](https://github.com/simonbengtsson/jsPDF-AutoTable/blob/master/src/painter.ts#L30), this broke in some very special scenarios where the lines are too close to the page end.

This simple check prevents this behavior by preventing any lines from printing by using zero remaining lines, which should be the case, as none can be printed on the current page.

### CODE REVIEW

**Comment by tarekis** [comment]
@simonbengtsson If you want to rebuild the package dist your own and want my commit to get rid of the ones I generated, please tell me, since I depend on the explicit commit sha of my branch as a npm dependency and need to update it if needed. I think my build has such a huge diff because the project dependencies lack determinism.

**Comment by simonbengtsson** [comment]
LGTM. Didn't really look into it, but I'll trust you on it.

**Comment by tarekis** [comment]
Oh sweet, thanks. Do you mind releasing this as a patch version? We'd love to get back to the official version instead of my sha. :)

**Comment by simonbengtsson** [comment]
No worries! For now, could you depend on the master branch or the commit? Wanna make sure it doesn't break anything before I release it.

**Comment by tarekis** [comment]
Sure thing, depending on my fork branch atm, so no hassle really. :)

**Pull request merged**
