### PR TITLE
Label handling and distribution overflow

### PR DESCRIPTION
**Pull request by Aleksey-Krylov**

### CODE REVIEW

**Comment by simonbengtsson** [comment]
Hi! Looks interesting!

1. Could you explain what the merge request is doing?
2. Only changes to code files are preferred (config.ts, widthCalculator.ts in this case). Feel free to submit a refactoring pull request first with library updates, eslint changes etc if you want though.
3. If the pull request contains multiple independent features, it would be optimal to submit them as multiple pull requests that can be merged independently.

I'll do a more in depth code review once the above is addressed.

**Comment by Aleksey-Krylov** [comment]
Oh, hi. This PR was a mistake, I didn't know I opened it. We use the local fork of your library for our project.

As continuation of this problem https://github.com/simonbengtsson/jsPDF-AutoTable/issues/686 we first started to produce our custom solution for colspan issues and after that we "went wild" and started putting our non-generic logic into lib. Because there are a lot of stuff that you cannot do just by using hooks, so we decided to edit the library itself.

**Comment by Aleksey-Krylov** [comment]
As for the interesting stuff for you: for minWidth and colspan > 2 we tried dividing minWidth by colspan evenly, but it produced really even results, especially when the cell spanned full table. Then we decided to produce something prettier and distribute the minWidth based on the proportions of other cells (what they want based on their content). 

So we added deferred calculation for this distribution, so these cells would wait for all "normal" ones to set their widths and after that distribute minwidth across the colspan proportionally.

**Comment by Aleksey-Krylov** [comment]
We've got a lot of custom stuff :)
image

**Comment by simonbengtsson** [comment]
Got it! Sounds interesting!

**Pull request closed without merging**
