### PR TITLE
Bug/nested columns and rows

### PR DESCRIPTION
**Pull request by RileyDavidson-Evans**

### CODE REVIEW

**Comment by RileyDavidson-Evans** [comment]
#427

**Comment by RileyDavidson-Evans** [comment]
Web View => screen shot 2019-01-30 at 8 19 31 am

**Comment by RileyDavidson-Evans** [comment]
Printed View =>
screen shot 2019-01-30 at 8 19 24 am

**Comment by simonbengtsson** [comment]
Reverted this PR now, it seems like it broke the rowspan and colspans examples? Also the rowspan in the html sample table on the first page.

**Pull request merged**
