### PR TITLE
feat(ApplyAutoTable): adding NodeJS support

### PR DESCRIPTION
**Pull request by rmdias**
By adding `jsPDF-AutoTable` into a method we can actually use it also in NodeJS :)

Updates
* [x] README
  - Usage
* [x] Tests
* [x] Examples

### CODE REVIEW

**Comment by rmdias** [comment]
#572

**Comment by simonbengtsson** [comment]
Awesome! Can you split the prettier code style migration and the nodejs pull request into two different ones to make for a better history and easier code review?

**Comment by rmdias** [comment]
@simonbengtsson Yep, could we wait till #584 gets merged? So I'll rebase this PR on `master`

**Comment by rmdias** [comment]
rebased @simonbengtsson :)

**Comment by simonbengtsson** [comment]
Do I understand correctly if this change is breaking for current users? Anyway we can make it so current usage is not affected but add a way for people who want to apply auto table when using the nodejs jspdf dist file?

**Comment by mmghv** [comment]
I think it can be achieved by having two separate distribution files, a default one for the browser which automatically calls `applyAutoTable()` on the global `jsPDF` object, and the other only exports `applyAutoTable()` which you can call on the node version of `jsPDF`.

**Comment by simonbengtsson** [comment]
Hmm, how about something like this?

```
export function applyAutoTable(jsPDF: any) {
  jsPDF.API.autoTable = autoTable

  jsPDF.API.autoTableSetDefaults = function(defaults) {
    setDefaults(defaults, this)
    return this
  }
  
  // ... and the other additions to the jsPDF api
}

// Backwards compatibility + no need to call appleAutoTable if using the default jspdf dist file
applyAutoTable(jsPDF);
```

**Comment by mmghv** [comment]
@simonbengtsson you mean we import the default `jsPDF` module and call `applyAutoTable();` on it every time? I'm not sure if importing the browser version of `jsPDF` in node environment would cause any problem or even if it doesn't would it be a good idea to import an irrelevant module in node.js? just sharing my thoughts.

**Comment by simonbengtsson** [comment]
Hmm, good point. How about this?
```
// main.ts

let initialized = false

function autoTable(...args) {
  if (!initialized) {
    applyAutoTable(require('jspdf'))
  }
  // ...
  return this
}

export function applyAutoTable(customJspdf) {
  jsPDF.API.autoTable = autoTable
  initialized = true
  // ... and the other additions to the jsPDF api
}
```

**Comment by simonbengtsson** [comment]
Good point. Importing different files might be the best solution then.

```js
import jsPDF from 'jspdf/dist/jspdf.node.min.js'
import 'jspdf-autotable/dist/jspdf.plugin.autotable-node.js'
```

With some refactorings we could probably make the `jspdf.plugin.autotable-node` pretty thin.

**Comment by mmghv** [comment]
> With some refactorings we could probably make the jspdf.plugin.autotable-node pretty thin.

Exactly.

There's also another option to detect the environment whether it's node or the browser and then `applyAutoTable(jsPDF);` if it's the browser.

But I still think separate dist files is a cleaner approach.

**Comment by simonbengtsson** [comment]
Yes. Seperate files enables people to use the browser version for nodejs (with some hacks) which has been the recommended option until jspdf added the nodejs dist file.

**Comment by rmdias** [comment]
Cool! Nice points. I'll work on it during the weekend, or early next week.

**Comment by rmdias** [comment]
Hi guys, I had a honeymoon break during last weeks, but I'm back :P 

Let me know what you think. @simonbengtsson @mmghv

**Comment by simonbengtsson** [comment]
Congrats to the wedding! Can you submit a separate pr with potential formatting + rebate with Master?

**Comment by rmdias** [comment]
formatting removed and rebased :) @simonbengtsson

**Comment by mmghv** [comment]
@rmdias Congrats, I wish you a happy life :)

I see that [node.ts](https://github.com/simonbengtsson/jsPDF-AutoTable/pull/583/files?file-filters%5B%5D=.lock&file-filters%5B%5D=.ts#diff-f2475756dd4ae35de6399cb10cb19351) copies all the content of [main.ts](https://github.com/simonbengtsson/jsPDF-AutoTable/blob/master/src/main.ts) except that it doesn't apply it to the global `jsPDF`, whe shouldn't have repeated code, that makes things difficult, we should abstract the common functionality.

How I imagine it is we can have the `main.ts` apply properties to a passed object, then we have `browser.ts` that only imports this file and applies it to the global `jsPDF`, and `node.ts` that only imports `main.ts` and exports the function that applies `autoTable` as is, the reason we should add `node.ts` that only imports and exports is for future use when we would need more setup for nodejs (if we ever do).

@simonbengtsson what do you think?

**Comment by simonbengtsson** [comment]
That sounds great @mmghv! In addition to avoid the duplicate code it would be nice to do the following changes as well:

- Don't commit yarn.lock to avoid potential conflicts with package-lock.json. Someone knows the recommended way for libraries? Maybe add it to gitignore?
- It does not matter too much since the types are generated. But do we need the duplicate types or can we just just the existing ones for the node dist file as well?
- Currently it breaks backwards compatibility since the text function is no longer exported in the same way. We could probably solve it somehow but a better solution is probably to stop exporting it and then bump major version mentioning this change in the release notes.

**Comment by mmghv** [comment]
- I don't know about yarn since I don't use it, but I believe that every lock file should be added to gitignore.
- I think we will not have duplicate types anymore because `node.ts` will only export one imported function from `main.ts`.
- I don't think applying the text function in a different file is considered breaking backward compatibility.

**Comment by simonbengtsson** [comment]
- Regarding lockfiles it seems to be recommended to commit it and libraries tend to only commit one. So let's keep package-lock.json in git, but not commit yarn.lock. This is also consistent with jspdf.
- Sounds good!
- Looked at it a second time now and you are right 👌

**Comment by simonbengtsson** [comment]
New idea for developer experience for this! How about simply try applying the api to both the normal jspdf dist file and the node js one? That way the user can choose which jspdf instance they want to use and autoTable will work either way. Will play around with that now.

**Comment by simonbengtsson** [comment]
Implemented in #612

**Pull request closed without merging**
