### PR TITLE
Dynamic Nested Table HTML check

### PR DESCRIPTION
**Pull request by RileyDavidson-Evans**
By checking if the table is data driven or HTML driven we can safely run the code which allows for dynamic html table row and column nesting

### CODE REVIEW

**Comment by RileyDavidson-Evans** [comment]
All demo tables in the examples are rendering and printing properly after this small adjustment.

Thanks for the check @simonbengtsson  !!

**Comment by simonbengtsson** [comment]
Have not looked into why, but there is a rowspan in the third "Basic" example is not working after this change?

screenshot 2019-01-31 at 10 08 22

Would be super cool if you added a "Nested table" example in for example the "Multiple tables" example document. That way we can make sure this doesn't break in future releases 👍

**Comment by simonbengtsson** [comment]
@RileyDavidson-Evans are you seeing the same same thing?

**Comment by RileyDavidson-Evans** [comment]
Hey @simonbengtsson I do as well ! I'll update the PR on Monday morning !

**Comment by RileyDavidson-Evans** [comment]
I'll add the nested table example as well

**Comment by simonbengtsson** [comment]
Probably fixed with the fixed to #445

**Pull request closed without merging**
