### PR TITLE
[v4] build updates

### PR DESCRIPTION
**Pull request by mmghv**
I was looking into maybe upgrading the build system to the more modern `Vite`, but I didn't find anything wrong with webpack and rollup honestly, you did a pretty good job with it.

So I just did the following updates:

### 1- Removed `./es` exports in `package.json`

it's not needed anymore after adding the `import` export field, ESM imports will correctly import the es build while `require` and others will default to the `umd` build.

- Tested all the failed scenarios from v3 which worked perfectly with v4 (vue3.2 build with vite2, angular17 dynamic imports in build, script normal and module)
- Tested tree-shaking-ability in ESM, works as expect, although not needed much as most of the library is used, but at least you don't get warning like the ones angular was giving with v3.

### 2- Upgraded transpile target from `ES5` to `ES6` (ES2015) and removed the `assign` polyfill

- By this, v4 officially doesn't support IE11
- Minimized build size decreased by 15% (33K -> 28K)

### 3- Moved devServer index.html to `./examples`

This solves a problem I was having most of the time while developing, with many actions in vscode the devserver was doing a full page reload (just by opening files or staging changes).

The problem was that it was watching the whole repo, including the `.git` directory which was changed sometimes simply by activating vscode window, with this update, it only watches the `examples` dir.

### 4- Added the info banner to the es build

---

All v4 goals have been met, next step I'll do some refactoring, then we will discuss some improvements that might require breaking changes.

I'll also look into rowspans missing support, I didn't review the already issued PR regarding rowspans yet, will do that after doing some refactoring and cleanup.

### CODE REVIEW

**Comment by simonbengtsson** [comment]
Looks great to me! I have not verified, but seems like the the moving of index.html to the examples folder might break the demo site hosted on github pages? I.e. the `hosting` npm script pushing code to the `gh-pages` branch.

**Comment by mmghv** [comment]
You can specify the root folder for github pages, this will need to be changed to `/examples` when v4 is published.

https://docs.github.com/en/pages/getting-started-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site#about-publishing-sources

**Comment by mmghv** [comment]
It could be solved with a custom github-pages workflow, but a simpler solution is to configure webpack devServer to only watch relevant files to prevent unwanted page reloads, which I did.

**Comment by simonbengtsson** [comment]
Awesome! Should we release a preview of V4 now or anything else major left?

**Comment by mmghv** [comment]
There're still somethings I want to go through which could require breaking changes to the api, A preview release to test the module system is fine though if that's what you want.

**Pull request merged**
