### PR TITLE
Colspan minwidth solution;

### PR DESCRIPTION
**Pull request by Never7Dice**
PR related to this issue https://github.com/simonbengtsson/jsPDF-AutoTable/issues/686

### CODE REVIEW

**Comment by Never7Dice** [comment]
@simonbengtsson when will you review this, please?

**Comment by Never7Dice** [comment]
So?

**Comment by simonbengtsson** [comment]
Sorry for the late review. I looked into it yesterday and think the changes might be somewhat problematic. I did update to support `minCellWidth` now in v3.5.10 however which means your example should work. Previously you had to set column width with colspan with `cellWidth`.  Can you test it?

**Comment by Never7Dice** [comment]
I did try 3.5.10 and I still have the same issue

```
    const doc = new jsPDF();

    const body: CellDef[][] = [];
    const head: CellDef[][] = [];

    head.push([
      {
        content: `Header 4`,
        colSpan: 4,
      }]);

    body.push([{
      content: 'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABBBBBBBB',
      colSpan: 2,
      styles: { minCellWidth: 55 },
    },
    {
      content: 'B',
      colSpan: 2,
      styles: { minCellWidth: 55 },
    }
    ]);

    autoTable(doc, {
      head: head,
      body: body,
      theme: 'grid',
    });

    doc.save('test.pdf');
```

image

**Comment by Never7Dice** [comment]
@simonbengtsson

**Comment by Never7Dice** [comment]
@simonbengtsson any updates on this one? Latest version still doesn't fix the small example mentioned above.

**Comment by simonbengtsson** [comment]
Got it. You needed it to adhere to cell styles as well and not only the columnStyles. If you add a comment about why this code is needed and a link to this PR it's I'll merge right away and release new version. Thanks for contributing.

**Comment by Never7Dice** [comment]
@simonbengtsson after update something has changed, but I still cannot understand what does it do. It's not something I would expect. I specify `minCellWidth` for the column and it starts to ignore the content. `minCellWidth` act as ration instead of constraint. Here's example:

    const body: CellDef[][] = [];
    const head: CellDef[][] = [];

    head.push([
      {
        content: `Header 4`,
        colSpan: 4,
      }]);

    body.push([{
      content: 'ABC',
      colSpan: 2,
      styles: { minCellWidth: 40 },
    },
    {
      content: '<h1><br></h1><h1>&#160;8 Buchstaben Hier unser <b>neues</b> PanelHier unser neues<u>Panel</u> Hier unser neues Hier Hier Hier</h1><div><br></div>',
      colSpan: 2,
      styles: { minCellWidth: 40 },
    }
    ]);

    autoTable(doc, {
      head: head,
      body: body,
      theme: 'grid',
      columnStyles: {
        0: { minCellWidth: 20 },
        1: { minCellWidth: 20 },
        2: { minCellWidth: 20 },
        3: { minCellWidth: 20 },
      },
    });

image

And if I remove `minCellWidth` constraints I get this:

image

I need to set min width for columns because I render content for some cells manually, but when I use minCellWidth dynamic width calculation based on content stops working...
For example if I only set         `0: { minCellWidth: 20 }` I get this weird 1:2 ratio

image

I think it's an issue, unexpected unintuitive behavior. It doesn't behave as constraint, any ideas?

**Comment by Never7Dice** [comment]
Here's some more weird examples

    const body: CellDef[][] = [];
    const head: CellDef[][] = [];

    head.push([
      {
        content: `Header 4`,
        colSpan: 4,
      }]);

    body.push([{
      content: 'ABC',
      colSpan: 2,
    },
    {
      content: '<h1><br></h1><h1>&#160;8 Buchstaben Hier unser <b>neues</b> PanelHier unser neues<u>Panel</u> Hier unser neues Hier Hier Hier</h1><div><br></div>',
      colSpan: 2,
    }
    ]);

    autoTable(doc, {
      head: head,
      body: body,
      theme: 'grid',
    });

image

and

    const body: CellDef[][] = [];
    const head: CellDef[][] = [];

    head.push([
      {
        content: `Header 4`,
        colSpan: 4,
      }]);

    body.push([{
      content: 'ABC',
      colSpan: 2,
    },
    {
      content: '<h1><br></h1><h1>&#160;8 Buchstaben Hier unser <b>neues</b> PanelHier unser neues<u>Panel</u> Hier unser neues Hier Hier Hier</h1><div><br></div>',
      colSpan: 2,
    }
    ]);

    autoTable(doc, {
      head: head,
      body: body,
      theme: 'grid',
      columnStyles: {
        0: { minCellWidth: 20 },
      },
    });

image

**Comment by Never7Dice** [comment]
To formalize what I want and expect to have: this code should make 2 visual columns with a header in a table of 190mm width. 1st column is taking colspan 2 and it's width is at least 100mm (for example column 0 is 50mm and column 1 is 50mm), 2nd column is taking colspan 2 and it's width is at least 20mm (for example column 3 is 10mm and column 4 is 10mm) [USING COLSPAN IS MANDATORY, THE REASON WHY IT'S USAGE IS NOT DESCRIBED HERE IS FOR SIMPLICITY]

    const body: CellDef[][] = [];
    const head: CellDef[][] = [];

    head.push([
      {
        content: `Header 4`,
        colSpan: 4,
      }]);

    body.push([{
      content: 'ABC',
      colSpan: 2,
      styles: { minCellWidth: 100 },
    },
    {
      content: '<h1><br></h1><h1>&#160;8 Buchstaben Hier unser <b>neues</b> PanelHier unser neues<u>Panel</u> Hier unser neues Hier Hier Hier</h1><div><br></div>',
      colSpan: 2,
      styles: { minCellWidth: 20 },
    }
    ]);

    autoTable(doc, {
      head: head,
      body: body,
      margin: 10,
      theme: 'grid',
      columnStyles: {
        0: { minCellWidth: 50 },
        1: { minCellWidth: 50 },
        2: { minCellWidth: 10 },
        3: { minCellWidth: 10 },
      },
    });

    doc.rect(this.sideTableMargin, this.sideTableMargin + 30, 100, 15);

What I get is this. 1st column took all available width, much more than it's minWidth or content, while 2nd column which actually could've love to have more width for it's content was capped at it's minwdith.
image

**Comment by Never7Dice** [comment]
Worst of all, that I cannot just say all structure columns to have `minCellWidth`. It produces completely static width calculation based on the ratio of minWidths ignoring the content!

    const body: CellDef[][] = [];
    const head: CellDef[][] = [];

    head.push([
      {
        content: `Header 4`,
        colSpan: 4,
      }]);

    body.push([{
      content: 'ABC',
      colSpan: 2,
    },
    {
      content: '<h1><br></h1><h1>&#160;8 Buchstaben Hier unser <b>neues</b> PanelHier unser neues<u>Panel</u> Hier unser neues Hier Hier Hier</h1><div><br></div>',
      colSpan: 2,
    }
    ]);

    autoTable(doc, {
      head: head,
      body: body,
      margin: 10,
      theme: 'grid',
      columnStyles: {
        0: { minCellWidth: 35 },
        1: { minCellWidth: 35 },
        2: { minCellWidth: 35 },
        3: { minCellWidth: 35 },
      }
    });

image

**Comment by Never7Dice** [comment]
@simonbengtsson please, it doesn't work as intended.

**Comment by Never7Dice** [comment]
@simonbengtsson still a critical issue

**Comment by Never7Dice** [comment]
I hope you are doing ok @simonbengtsson , I'm starting to worry if you are alive and well :(

**Comment by Never7Dice** [comment]
Any news @simonbengtsson ?

**Pull request closed without merging**
