### PR TITLE
browserlist added to support IE 11

### PR DESCRIPTION
**Pull request by janmas**

### CODE REVIEW

**Comment by simonbengtsson** [comment]
Sorry for the late review. Can you resubmit without the lockfile and dist file changes? Those will be updated automatically during new version build.

**Comment by simonbengtsson** [comment]
What is blocking IE11 support today?

**Comment by janmas** [comment]
> Sorry for the late review. Can you resubmit without the lockfile and dist file changes? Those will be updated automatically during new version build.

No problem. Resubmit done as requested :-)

**Comment by simonbengtsson** [comment]
I meant why is the browserList addition in package.json needed. I thought the plugin supported internet explorer 10 and 11 already 🤔

**Comment by janmas** [comment]
> Thanks! What is blocking IE11 support today? Ie what is this fix actually doing?

The fix will tell the typescript compiler to transpile TS into JS which could be also run in IE11 which - for example - does not support arrow functions (https://caniuse.com/arrow-functions).

**Comment by janmas** [comment]
> I meant why is the browserList addition in package.json needed. I thought the plugin supported internet explorer 10 and 11 already 🤔

In our case the generated JS (without the browserList) contained arrow functions and because of that the library did not work in IE11.

**Comment by simonbengtsson** [comment]
Changes in this PR now added as part of https://github.com/simonbengtsson/jsPDF-AutoTable/commit/737e5c3c7f7b3cecfbed910f147b0b782eb632c4 and will be released in next version

**Pull request closed without merging**
