### PR TITLE
add es import option in the package exports

### PR DESCRIPTION
**Pull request by robertIsaac**
as suggested in https://github.com/angular/angular-cli/issues/26888#issuecomment-1906034537

### CODE REVIEW

**Comment by mmghv** [comment]
This will be resolved in [v4](https://github.com/simonbengtsson/jsPDF-AutoTable/issues/997) when we move away from the default export and rework the build system.

For now you could explicitly import `jspdf-autotable/es` for the ESM version.

@simonbengtsson What do you think? I suggest leaving this as-is right now so we don't introduce any breaking changes in v3.

**Comment by mmghv** [comment]
Note: this seems to be an issue **only** for dynamic imports `await import(...)`, for static import it works just fine `import autoTable from 'jspdf-autotable'`.

**Comment by robertIsaac** [comment]
> For now you could explicitly import `jspdf-autotable/es` for the ESM version.

Unfortunately it throw an error
https://github.com/robertIsaac/jspdf-autotable-error-reprod
Here is example

You can read the discussion here
https://github.com/angular/angular-cli/issues/26888#issuecomment-1906034537

**Comment by mmghv** [comment]
I was able to get it to work after setting `module` and `moduleResolution` TS config to `nodeNext` as mentioned in the thread, I also needed to add `type: "module"` in `package.json`.

But without all this, I was able to convert the dynamic import to static import and it worked fine in production, do you really need the dynamic import? this seems to be an issue with esbuild in angular and default exports for CommonJS libs transformed from ESM.

**Comment by robertIsaac** [comment]
Yeah I need the dynamic import so I don't load the package (along others) unless the user started exporting, this helps a lot with the initial build size

**Comment by robertIsaac** [comment]
> Have you tried the TS config solution?

No it will probably cause even more problems but I will try it later today or tomorrow when I have time

**Comment by simonbengtsson** [comment]
Didn't know about the 'import' option. Added it now now in the v4 branch!

**Pull request closed without merging**
